/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MangaService } from "../manga.service";
import { MangaCreateInput } from "./MangaCreateInput";
import { Manga } from "./Manga";
import { MangaFindManyArgs } from "./MangaFindManyArgs";
import { MangaWhereUniqueInput } from "./MangaWhereUniqueInput";
import { MangaUpdateInput } from "./MangaUpdateInput";

export class MangaControllerBase {
  constructor(protected readonly service: MangaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Manga })
  async createManga(@common.Body() data: MangaCreateInput): Promise<Manga> {
    return await this.service.createManga({
      data: data,
      select: {
        createdAt: true,
        genres: true,
        id: true,
        releaseYear: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Manga] })
  @ApiNestedQuery(MangaFindManyArgs)
  async mangaItems(@common.Req() request: Request): Promise<Manga[]> {
    const args = plainToClass(MangaFindManyArgs, request.query);
    return this.service.mangaItems({
      ...args,
      select: {
        createdAt: true,
        genres: true,
        id: true,
        releaseYear: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Manga })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async manga(
    @common.Param() params: MangaWhereUniqueInput
  ): Promise<Manga | null> {
    const result = await this.service.manga({
      where: params,
      select: {
        createdAt: true,
        genres: true,
        id: true,
        releaseYear: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Manga })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateManga(
    @common.Param() params: MangaWhereUniqueInput,
    @common.Body() data: MangaUpdateInput
  ): Promise<Manga | null> {
    try {
      return await this.service.updateManga({
        where: params,
        data: data,
        select: {
          createdAt: true,
          genres: true,
          id: true,
          releaseYear: true,
          summary: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Manga })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteManga(
    @common.Param() params: MangaWhereUniqueInput
  ): Promise<Manga | null> {
    try {
      return await this.service.deleteManga({
        where: params,
        select: {
          createdAt: true,
          genres: true,
          id: true,
          releaseYear: true,
          summary: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
